# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataImportData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, key: str=None, value: object=None):  # noqa: E501
        """DataImportData - a model defined in Swagger

        :param key: The key of this DataImportData.  # noqa: E501
        :type key: str
        :param value: The value of this DataImportData.  # noqa: E501
        :type value: object
        """
        self.swagger_types = {
            'key': str,
            'value': object
        }

        self.attribute_map = {
            'key': 'key',
            'value': 'value'
        }
        self._key = key
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'DataImportData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataImport_data of this DataImportData.  # noqa: E501
        :rtype: DataImportData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this DataImportData.


        :return: The key of this DataImportData.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this DataImportData.


        :param key: The key of this DataImportData.
        :type key: str
        """

        self._key = key

    @property
    def value(self) -> object:
        """Gets the value of this DataImportData.


        :return: The value of this DataImportData.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this DataImportData.


        :param value: The value of this DataImportData.
        :type value: object
        """

        self._value = value
